nodes:
  vars:
    user: sindri
    primary_group: "{{ user }}"
    additional_groups:
      - sudo
      - ssh-user
    ssh_public_key_path: ~/.ssh/sindri.pub
  hosts:
    vanaheim:
    jotunheim:
    nilfheim:

control_plane:
  hosts:
    midgard:
      ansible_connection: local
