apiVersion: v1
data:
  DB_HOST: cGVyc29uYWxpZGFkZXMtZGItc3Zj
  DB_NAME: cGVyc29uYWxpZGFkZXM=
  DB_PASSWORD: MXJNeEQrUnA1bUo0bFNBUnpRSHo2b0NIZk9lZGY1a2FMNFFxN0pqWjcvbz0=
kind: Secret
metadata:
  creationTimestamp: "2026-07-06T17:06:21Z"
  name: personalidades-server-secret
  namespace: default
  resourceVersion: "313709"
  uid: d23fb3d4-a621-4a3d-82b5-a8ea882503e9
type: Opaque
