apiVersion: v1
kind: Pod
metadata:
  creationTimestamp: "2026-07-06T16:51:09Z"
  generation: 1
  labels:
    app: personalidades-server
  name: personalidades-server
  namespace: default
  resourceVersion: "311737"
  uid: c4540727-5f2f-46f6-9755-9e267d8b59bb
spec:
  containers:
    - image: localhost/personalidades-server:latest
      imagePullPolicy: Never
      name: personalidades-server
      ports:
        - containerPort: 8000
          protocol: TCP
      resources: {}
      terminationMessagePath: /dev/termination-log
      terminationMessagePolicy: File
      volumeMounts:
        - mountPath: /var/run/secrets/kubernetes.io/serviceaccount
          name: kube-api-access-9zvzs
          readOnly: true
      envFrom:
        - secretRef:
            name: personalidades-server-secret
  dnsPolicy: ClusterFirst
  enableServiceLinks: true
  preemptionPolicy: PreemptLowerPriority
  priority: 0
  restartPolicy: Always
  schedulerName: default-scheduler
  securityContext: {}
  serviceAccount: default
  serviceAccountName: default
  terminationGracePeriodSeconds: 30
  tolerations:
    - effect: NoExecute
      key: node.kubernetes.io/not-ready
      operator: Exists
      tolerationSeconds: 300
    - effect: NoExecute
      key: node.kubernetes.io/unreachable
      operator: Exists
      tolerationSeconds: 300
  volumes:
    - name: kube-api-access-9zvzs
      projected:
        defaultMode: 420
        sources:
          - serviceAccountToken:
              expirationSeconds: 3607
              path: token
          - configMap:
              items:
                - key: ca.crt
                  path: ca.crt
              name: kube-root-ca.crt
          - downwardAPI:
              items:
                - fieldRef:
                    apiVersion: v1
                    fieldPath: metadata.namespace
                  path: namespace
status:
  phase: Pending
  qosClass: BestEffort
