apiVersion: v1
data:
  POSGRES_PASSWORD: b0RCbmREVXBtcjk1VXJRRHlkMkh5cytFWGFubGVxaTkycUVVb3pBVjhkOD0=
  POSGRES_USER: Z29waGVy
  POSTGRES_DB: cGVyc29uYWxpZGFkZXM=
kind: Secret
metadata:
  creationTimestamp: "2026-07-06T17:02:36Z"
  name: personalidades-db-secret
  namespace: default
  resourceVersion: "313255"
  uid: fc6fa45b-32d9-488a-b9c3-1b1ec8c5524f
type: Opaque
