apiVersion: v1
data:
  POSTGRES_DB: cGVyc29uYWxpZGFkZXM=
  POSTGRES_PASSWORD: MXJNeEQrUnA1bUo0bFNBUnpRSHo2b0NIZk9lZGY1a2FMNFFxN0pqWjcvbz0=
  POSTGRES_USER: Z29waGVy
kind: Secret
metadata:
  creationTimestamp: "2026-07-06T16:36:55Z"
  name: personalidades-db-secret
  namespace: default
  resourceVersion: "309972"
  uid: 1714208b-2d9e-4022-b74b-f68fdbc70a88
type: Opaque
